name: FB Blacklist Bot

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'  # перезапуск кожні 5 годин

jobs:
  run_bot:
    runs-on: ubuntu-latest
    timeout-minutes: 300  # 5 годин максимум

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python main.py